#!/bin/bash
su
[A[C[C
[A[A[A[C[C[C[C[C[C[C[C[C[C[C[B[C[A[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[A[C[C
#!/bin/bash
su
[A[B[B[A[A[C[C betty
[A[C[C[C[C[C[Cbetty
